<script type="text/javascript">
	require([
		'jquery',
		'Lof_All/lib/bootstrap/js/bootstrap.min',
		<?php if($this->helper("Lof\All\Helper\Data")->getConfig("enable_owlcarousel")): ?>
		"Lof_All/lib/owl.carousel/owl.carousel.min",
	<?php endif; ?>
	], function () {
		jQuery(document).ready(function($) {
			if(jQuery(".products-lookbook.owl").length > 0 ) {
				var owlItems = [];
				jQuery(".products-lookbook.owl").each( function(){
					var owlCarousel = jQuery(this).find(".owl-carousel");
					var owlId = jQuery(owlCarousel).attr("id");
					jQuery(this).addClass("hasOwl");
					var config = [];
					owlItems[jQuery(owlCarousel).attr("id")] = true;
					if(jQuery(owlCarousel).data('nav') !='undefined'){
						config['nav'] = jQuery(owlCarousel).data('nav');
					}
					if(jQuery(owlCarousel).data('dot')  !='undefined'){
						config['dot'] = jQuery(owlCarousel).data('dot');
					}
					if(jQuery(owlCarousel).data('autoplay')  !='undefined'){
						config['autoplay'] = jQuery(owlCarousel).data('autoplay');
					}
					if(jQuery(owlCarousel).data('autoplay-timeout')  !='undefined'){
						config['autoplayTimeout'] = jQuery(owlCarousel).data('autoplay-timeout');
					}
					if(jQuery(owlCarousel).data('autoplay-pauonhover')  !='undefined'){
						config['autoplayHoverPause'] = jQuery(owlCarousel).data('autoplay-pauonhover');
					}
					if(jQuery(owlCarousel).data('rtl') !='undefined'){
						config['rtl'] = jQuery(owlCarousel).data('rtl');
					}
					if(jQuery(owlCarousel).data('items')  !='undefined'){
						
						config['items'] = jQuery(owlCarousel).data('items');
					}
					if(jQuery(owlCarousel).data('loop') !='undefined'){
						config['loop'] = jQuery(owlCarousel).data('loop');
					}
					if(jQuery(owlCarousel).data('mousedrag') !='undefined'){
						config['mouseDrag'] = jQuery(owlCarousel).data('mousedrag');
					}
					if(jQuery(owlCarousel).data('pulldrag') !='undefined'){
						config['pullDrag'] = jQuery(owlCarousel).data('pulldrag');
					}
					if(jQuery(owlCarousel).data('freedrag') !='undefined'){
						config['freeDrag'] = jQuery(owlCarousel).data('freedrag');
					}
					if(jQuery(owlCarousel).data('stagepadding') !='undefined'){
						config['stagePadding'] = jQuery(owlCarousel).data('stagepadding');
					}
					if(jQuery(owlCarousel).data('lazyload') !='undefined'){
						config['lazyLoad'] = jQuery(owlCarousel).data('lazyload');
					}
					if(jQuery(owlCarousel).data('margin') !='undefined'){
						config['margin'] = jQuery(owlCarousel).data('margin');
					}
					var mobile_items = 1;
					if(jQuery(owlCarousel).data('mobile-items') !='undefined'){
						mobile_items = jQuery(owlCarousel).data('mobile-items');
					}
					var tablet_small_items = 3;
					if(jQuery(owlCarousel).data('tablet-small-items') !='undefined'){
						tablet_small_items = jQuery(owlCarousel).data('tablet-small-items');
					}
					var tablet_items = 3;
					if(jQuery(owlCarousel).data('tablet-items') !='undefined'){
						tablet_items = jQuery(owlCarousel).data('tablet-items');
					}
					var portrait_items = 4;
					if(jQuery(owlCarousel).data('portrait-items') !='undefined'){
						portrait_items = jQuery(owlCarousel).data('portrait-items');
					}
					var large_items = 5;
					if(jQuery(owlCarousel).data('large-items') !='undefined'){
						large_items = jQuery(owlCarousel).data('large-items');
					}
					var large_max_items = 6;
					if(jQuery(owlCarousel).data('large-max-items') !='undefined'){
						large_max_items = jQuery(owlCarousel).data('large-max-items');
					}
					config['responsive'] = {
						0 : {items: mobile_items},
						480 : {items: tablet_small_items},
						640 : {items: tablet_items},
						768 : {items: portrait_items},
						980 : {items: large_items},
						1200 : {items: large_max_items}
					};
					jQuery(owlCarousel).owlCarousel(config);
					jQuery(".owl-left").click(function(){
						var owlCarousel = jQuery("#"+jQuery(this).data("owlid"));
						owlCarousel.trigger('prev.owl.carousel');
						return false;
					});
					jQuery(".owl-right").click(function(){
						var owlCarousel = jQuery("#"+jQuery(this).data("owlid"));
						owlCarousel.trigger('next.owl.carousel');
						return false;
					});
				});
			}
		});
	});
</script>